name: 'Auto release draft'
on:
  create:
jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest
    steps:
      - name: Create a release draft for a version tag
        uses: jgoergen/githubActionDemo@v1.03
        id: create-release-draft
        with:
          repo-token: ${{ secrets.TOKEN }}
      - name: Print the URL of the release draft
        if: steps.create-release-draft.outputs.release-url != ''
        run: echo ${{ steps.create-release-draft.outputs.release-url }}
